export type RolePreset = {
  id: string;
  name: string;
  rights: string[];
};

export const ROLE_PRESETS: RolePreset[] = [
  {
    id: "ehs-director",
    name: "EHS Director",
    rights: [
      "Dashboard.View",
      "Dashboard.Export",
      "Safety.Incident.View",
      "Safety.Incident.Create",
      "Safety.Incident.Update",
      "Safety.Incident.Delete",
      "Safety.LOTO.Manage",
      "PPE.Create",
      "PPE.Issue",
      "PPE.Request",
      "Safety.Permit.View",
      "Safety.Permit.Create",
      "Safety.Permit.Approve",
      "Safety.Observation.Create",
      "Safety.Inspection.Complete",
      "Safety.Hazard.Report",
      "Health.Claim.View",
      "Health.Claim.Submit",
      "Health.Claim.Manage",
      "Health.MedicalRecords.View",
      "Health.SDS.View",
      "Compliance.Document.View",
      "Compliance.Document.Upload",
      "Compliance.Document.Approve",
      "Compliance.Audit.Manage",
      "Compliance.Training.Manage",
      "Compliance.Regulation.View",
      "Compliance.Create",
      "Compliance.View",
      "Compliance.Update",
      "Compliance.Delete",
      "Analytics.View",
      "Analytics.Export",
      "Analytics.Action.Manage",
      "System.Users.Manage",
      "System.Roles.Manage",
      "System.Settings.Manage",
      "System.AuditLog.View",
      "System.Regulations.Manage",
      "System.Categories.Manage",
    ],
  },
  {
    id: "ehs-lead",
    name: "EHS Lead",
    rights: [
      "Dashboard.View",
      "Dashboard.Export",
      "Safety.Incident.View",
      "Safety.Incident.Create",
      "Safety.Incident.Update",
      "Safety.Incident.Delete",
      "Safety.LOTO.Manage",
      "PPE.Create",
      "PPE.Issue",
      "PPE.Request",
      "Safety.Permit.View",
      "Safety.Permit.Create",
      "Safety.Permit.Approve",
      "Safety.Observation.Create",
      "Safety.Inspection.Complete",
      "Safety.Hazard.Report",
      "Health.Claim.View",
      "Health.Claim.Submit",
      "Health.Claim.Manage",
      "Health.MedicalRecords.View",
      "Health.SDS.View",
      "Compliance.Document.View",
      "Compliance.Document.Upload",
      "Compliance.Document.Approve",
      "Compliance.Audit.Manage",
      "Compliance.Training.Manage",
      "Compliance.Regulation.View",
      "Compliance.Create",
      "Compliance.View",
      "Compliance.Update",
      "Compliance.Delete",
      "Analytics.View",
      "Analytics.Export",
      "Analytics.Action.Manage",
    ],
  },
  {
    id: "ehs-manager",
    name: "EHS Manager",
    rights: [
      "Dashboard.View",
      "Dashboard.Export",
      "Safety.Incident.View",
      "Safety.Incident.Create",
      "Safety.Incident.Update",
      "Safety.LOTO.Manage",
      "PPE.Create",
      "PPE.Issue",
      "Safety.Permit.View",
      "Safety.Permit.Create",
      "Safety.Permit.Approve",
      "Safety.Observation.Create",
      "Safety.Inspection.Complete",
      "Safety.Hazard.Report",
      "Health.Claim.View",
      "Health.Claim.Submit",
      "Health.Claim.Manage",
      "Health.SDS.View",
      "Compliance.Document.View",
      "Compliance.Document.Upload",
      "Compliance.Document.Approve",
      "Compliance.Audit.Manage",
      "Compliance.Training.Manage",
      "Compliance.Regulation.View",
      "Compliance.Create",
      "Compliance.View",
      "Compliance.Update",
      "Analytics.View",
      "Analytics.Export",
      "Analytics.Action.Manage",
    ],
  },
  {
    id: "supervisor",
    name: "Supervisor",
    rights: [
      "Dashboard.View",
      "Safety.Incident.View",
      "Safety.Incident.Create",
      "Safety.Incident.Update",
      "Safety.LOTO.Manage",
      "PPE.Issue",
      "PPE.Request",
      "Safety.Permit.View",
      "Safety.Permit.Approve",
      "Safety.Observation.Create",
      "Safety.Inspection.Complete",
      "Safety.Hazard.Report",
      "Health.Claim.View",
      "Health.Claim.Submit",
      "Health.SDS.View",
      "Compliance.Document.View",
      "Compliance.Create",
      "Compliance.Update",
      "Compliance.Regulation.View",
      "Analytics.View",
    ],
  },
  {
    id: "worker",
    name: "Worker",
    rights: [
      "Dashboard.View",
      "Safety.Observation.Create",
      "Safety.Inspection.Complete",
      "Safety.Hazard.Report",
      "Health.SDS.View",
      "Compliance.Document.View",
      "PPE.Request",
    ],
  },
];

export const DEFAULT_PRESET_ID = "ehs-director";

export function getRolePreset(id: string): RolePreset | undefined {
  return ROLE_PRESETS.find((preset) => preset.id === id);
}

export function getPresetRights(id: string): string[] {
  return getRolePreset(id)?.rights ?? [];
}

export function getPresetRightCount(id: string): number {
  return getPresetRights(id).length;
}
